version: '3.8'

services:
  postgis:
    build: .
    container_name: postgis_container
    image: postgis/postgis:latest
    platform: linux/amd64 # I'm using an M2 Macbook Air
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: census_db
      POSTGRES_MULTIPLE_EXTENSIONS: postgis,postgis_topology,postgis_tiger_geocoder
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./shapefiles:/shapefiles
      - ./acs_summary_file:/acs_summary_file
      # - /etc/localtime:/etc/localtime
      # - ./import_shapefiles.sh:/import_shapefiles.sh
    ports:
      - "5432:5432"
    # command: -c "chmod +x /import_shapefiles.sh"
    restart: always
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - postgis

volumes:
  db-data: